### ISSUE TITLE
GHC 8.4.2: "Got error while processing diagnostics: unable to load package `integer-gmp-1.0.2.0'"

### ISSUE THREAD

**Issue by runeksvendsen** [alanz/vscode-hie-server#89] opened 2018-06-03 15:24 UTC
I'm getting the error below when I try to view `src/Paths.hs` in VS Code from the following repo/branch: https://github.com/runeksvendsen/crypto-venues/tree/graph

`Got error while processing diagnostics: unable to load package 'integer-gmp-1.0.2.0'`

I'm using the Stack resolver `nightly-2018-05-30` (GHC 8.4.2), which matches the output of `hie --compiler`.

**Comment by alanz** [comment] 2018-06-03 19:42
Is this on macos? I think there is issue around integer-gmp on that platform and/or windows

Does the project build outside of hie?

**Comment by runeksvendsen** [comment] 2018-06-04 14:30
Oh, yes, I forgot to mention I'm on MacOS.

The aforementioned repo/branch (https://github.com/runeksvendsen/crypto-venues/tree/graph) does not build, but I've tried out-commenting the errors in `src/Paths.hs`, so that the project builds, and I still get the `integer-gmp`-related error.

**Comment by Tehnix** [comment] 2018-06-04 15:40
I *think* the issue with integer-gmp was fixed in 8.4.3, but I’m not entirely sure. Would you be able to test against a resolver with that GHC version?

**Comment by runeksvendsen** [comment] 2018-06-04 19:54
@Tehnix How do I build `hie` with GHC 8.4.3 inside?

I tried changing Stack resolver for my project to `nightly-2018-06-02`, but now I get an error from ghc-mod:

```
[ghcmod]
Bad interface file: /Users/runesvendsen/.stack/snapshots/x86_64-osx/nightly-2018-06-02/8.4.3/lib/x86_64-osx-ghc-8.4.3/http-client-0.5.12.1-Jz7lKEONVEuEVWDof4BXPO/Network/HTTP/Client.hi
    mismatched interface file versions (wanted "8042", got "8043")
```

which, I assume, is related to the mismatch between `hie`s compiler (ghc-8.4.2) and what's now used by my project.

**Comment by alanz** [comment] 2018-06-04 20:01
hie current master does support GHC 8.4.3, if you install it via the makefile, and update the vscode plugin to 0.0.18 (which has a bug for windows, must turn tracing to verbose else hie wont start, #90 )

**Comment by runeksvendsen** [comment] 2018-06-05 16:44
I updated `hie` to current master and built `hie-8.4.3` (`hie --compiler` now says `ghc-8.4.3`), but unfortunately VS Code still gives me the error `Got error while processing diagnostics: unable to load package 'integer-gmp-1.0.2.0'` using `vscode-hie-server` version 0.0.19.

**Comment by Bubba** [comment] 2018-06-18 22:12
This is caused by a known issue with GHC, in the meantime try the workaround here: https://github.com/haskell/haskell-ide-engine/issues/562

**Comment by runeksvendsen** [comment] 2018-06-27 18:55
@Bubba which workaround are you referring to?

**Comment by Bubba** [comment] 2018-06-27 19:03
@runeksvendsen The workaround I used was renaming `/Users/luke/.stack/programs/x86_64-osx/ghc-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o` to some other random file

**Comment by runeksvendsen** [comment] 2018-06-28 07:00
Thank you @Bubba! That got rid of the error.

Feel free to close this issue if you feel like it (not sure whether or not I should close it, given that a workaround is required).

**Comment by AlexeyRaga** [comment] 2019-01-06 06:51
Do we have a solution for this issue?
I started having `Got error while processing diagnostics: unable to load package `integer-gmp-1.0.2.0'` on GHC 8.4.4 after updating to the latest commit.

I renamed all the `HSinteger-gmp-1.0.2.0.o` I have found for that GHC, but I am still having this problem...

At the same time, `cabal new-build` works fine.

**Comment by AlexeyRaga** [comment] 2019-01-06 07:06
Oh, actually, I have found yet another occurrence of `HSinteger-gmp-1.0.2.0.o` and renaming it helped.

**Comment by jneira** [comment] 2020-01-09 07:24
I think we could close this one as it has a known workaround and it is documented

**Closed by jneira** 2020-01-09 07:24 UTC
