### ISSUE TITLE
Extension isn't starting

### ISSUE THREAD

**Issue by Imfractical** [alanz/vscode-hie-server#86] opened 2018-05-24 04:24 UTC
On Windows 10 with VSCode 1.23.1, and GHC 8.4.2. Installed HIE with stack; `hie` works, but the extension doesn't load when I open up a Haskell file. There's no output window or anything in the developer console. Trying to do a command from the pallet gives, e.g. "command 'hie.commands.showType' not found". I'm really stumped here, any help?

**Comment by tristangreeno** [comment] 2018-07-01 07:45
I have the exact same problem on Windows 10.

**Comment by supermari0** [comment] 2018-07-06 17:06
I have this problem as well.

If it helps, I see this in the output window under the extension host log:

```
[2018-07-06 11:52:05.260] [exthost1] [info] ExtensionService#_doActivateExtension alanz.vscode-hie-server {"startup":false,"activationEvent":"onLanguage:haskell"}
```

However, I see nothing in the extension log itself. I also cannot find an hie.log file anywhere on the computer.

**Comment by bratfizyk** [comment] 2018-09-15 00:01
+1. Same on my machine, which is running on Linux Mint 19. I can see something like:

`[2018-09-15 01:56:09.255] [exthost2] [info] extension host started
[2018-09-15 01:56:09.332] [exthost2] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2018-09-15 01:56:09.332] [exthost2] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/out/extension
[2018-09-15 01:56:09.343] [exthost2] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-09-15 01:56:09.343] [exthost2] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2018-09-15 01:56:09.416] [exthost2] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-09-15 01:56:09.416] [exthost2] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2018-09-15 01:56:09.674] [exthost2] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-09-15 01:56:09.674] [exthost2] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/out/extension
[2018-09-15 01:56:09.686] [exthost2] [info] ExtensionService#_doActivateExtension vscode.search-rg {"startup":true,"activationEvent":"*"}
[2018-09-15 01:56:09.686] [exthost2] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/search-rg/out/extension
[2018-09-15 01:56:09.693] [exthost2] [info] eager extensions activated`

**Comment by alanz** [comment] 2018-09-15 13:13
There is a file called `hie-vscode.bat` (and `hie-vscode.sh`) that is executed to start the extension.

When it is called, it expects to have `hie-wrapper` and (at least) `hie` in its path.

**Comment by bratfizyk** [comment] 2018-09-15 22:04
The thing is: both "hie" and "hie-wrapper" are included in PATH. When I run my console and run these command, everything just runs.

**Comment by alanz** [comment] 2018-09-16 07:30
Sometimes the path is different for an interactive shell vs a non-interactive one.

e.g. for `bash` is is normally better to set the path in `~/.profile` than in `~/.bachrc`, then it is used for both.

**Comment by Kleislii** [comment] 2018-12-14 16:02
Excuse me, how can I get the extension to run after all?
I'm at a loss.
Windows 10, GHC 8.4.4
`hie` and `hie-wrapper` are both already in PATH, `C:\Users\〇〇\AppData\Roaming\local\bin`

**Comment by lem0n4de** [comment] 2019-06-03 21:57
I am running this extension on NixOS 19.03. Extension is installed, but there is no logs of it in `Extension Host` log of vscode.
```
[2019-06-04 00:49:33.587] [exthost] [info] extension host started
[2019-06-04 00:49:33.619] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:33.619] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/lgphpv7cpq8lrzxsvknjaf9dal350ysl-vscode-1.33.1/lib/vscode/resources/app/extensions/debug-auto-launch/dist/extension
[2019-06-04 00:49:33.685] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:33.685] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/lgphpv7cpq8lrzxsvknjaf9dal350ysl-vscode-1.33.1/lib/vscode/resources/app/extensions/emmet/dist/extension
[2019-06-04 00:49:33.773] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:33.773] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/lgphpv7cpq8lrzxsvknjaf9dal350ysl-vscode-1.33.1/lib/vscode/resources/app/extensions/git/dist/main
[2019-06-04 00:49:33.989] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:33.990] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/lgphpv7cpq8lrzxsvknjaf9dal350ysl-vscode-1.33.1/lib/vscode/resources/app/extensions/merge-conflict/dist/extension
[2019-06-04 00:49:34.012] [exthost] [info] ExtensionService#_doActivateExtension CoenraadS.bracket-pair-colorizer-2 {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:34.012] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/4g2yikack0f2gbaazy3vb4p1s9f94z0p-vscode-extensions-1.33.1/share/vscode/extensions/CoenraadS.bracket-pair-colorizer-2/out/src/extension
[2019-06-04 00:49:34.129] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:34.129] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/4g2yikack0f2gbaazy3vb4p1s9f94z0p-vscode-extensions-1.33.1/share/vscode/extensions/Gruntfuggly.todo-tree/extension
[2019-06-04 00:49:35.305] [exthost] [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:35.305] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/4g2yikack0f2gbaazy3vb4p1s9f94z0p-vscode-extensions-1.33.1/share/vscode/extensions/christian-kohler.path-intellisense/out/src/extension
[2019-06-04 00:49:35.421] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"activationEvent":"*"}
[2019-06-04 00:49:35.421] [exthost] [info] ExtensionService#loadCommonJSModule /nix/store/4g2yikack0f2gbaazy3vb4p1s9f94z0p-vscode-extensions-1.33.1/share/vscode/extensions/eamodio.gitlens/dist/extension
[2019-06-04 00:49:35.591] [exthost] [info] eager extensions activated
```

Here are my settings.
```
{
  "languageServerHaskell.enableHIE":true,
  "languageServerHaskell.hieExecutablePath":"/nix/store/xn3xdxvcrf8pha9fq2b7rg4dw63k0bx0-haskell-ide-engine-combined/bin/hie",
  "languageServerHaskell.hlintOn":true,
}
```


Both hie and hie-wrapper is on PATH, they are installed on root user and can be used by my user.
```
$ ~  which which hie hie-wrapper
/run/current-system/sw/bin/hie
/run/current-system/sw/bin/hie-wrapper
```

And because of curiosity, I installed atom editor and hie works there. So it is not the cause. I don't know why but this extension is not even logged, despite being shown in extensions page.

**Comment by sheyll** [comment] 2019-08-22 16:03
I have this problem, too.

I run NixOS 19.03.

**Comment by jneira** [comment] 2020-01-09 07:20
I cant reproduce it in windows 10 wit latest versions of the vscode extension and hie, otoh logging had changed a lot.
Not sure about NixOs though.
@Imfractical @tristangreeno @supermari0 @bratfizyk @lem0n4de @sheyll could you all give a try with latest versions?

**Comment by bratfizyk** [comment] 2020-01-09 15:56
Sure, will do. I'll try it with NixOS and Ubuntu.
Busy time now, but over the weekend I'll find a moment.

**Comment by pweids** [comment] 2020-05-19 15:34
I'm also getting this problem on macOS. The Extension Host log shows `[2020-05-19 10:31:13.709] [exthost] [info] ExtensionService#_doActivateExtension alanz.vscode-hie-server {"startup":false,"extensionId":{"value":"alanz.vscode-hie-server","_lower":"alanz.vscode-hie-server"},"activationEvent":"onLanguage:haskell"}`

I have hie in the PATH, and I put the bin (~/.local/bin/) as the Hie Executable Path in settings. I compiled it for ghc-8.8.3, which is what my project is using.

**Comment by jneira** [comment] 2020-05-25 07:53
Closing it, feel free to open a new one if you continue experiencing it

**Closed by jneira** 2020-05-25 07:53 UTC
Labels: status: need confirmation
