### ISSUE TITLE
doesn't work on 1.33

### ISSUE THREAD

**Issue by mikelpr** [alanz/vscode-hie-server#148] opened 2019-04-05 02:41 UTC
hie is not started. no warnings no errors. I just downgraded to 1.32.3 and it works again and there's #147 so I guess the insider build hit stable today as 1.33

**Comment by AlexeyRaga** [comment] 2019-04-05 03:19
Same here.

**Comment by AlexeyRaga** [comment] 2019-04-05 03:50
I just tried to upgrade deps for `vscode-hie-server` and got an error that it couldn't be activated because `justusadam.language-haskell` couldn't be activated.
And `justusadam.language-haskell` is not activate because of the "missing property `source`".
I am not sure if I am debugging it correctly though...

**Comment by NickSeagull** [comment] 2019-04-05 07:48
Hit this issue too, let me know if I can do something to help @alanz 😄

**Comment by alanz** [comment] 2019-04-05 07:51
I have very little knowledge of this platform, the extension is basically cargo-cult programming, so if you have some knowledge and can help, a PR would be great.

**Comment by AlexeyRaga** [comment] 2019-04-05 10:44
I tracked down the issue to a particular line of code and figured out a workaround. But since I am not into JS/TS/VSCode, I am not entirely sure if my workaround sounds.
Whoever is more experienced with TS/JS, please have a look: https://github.com/JustusAdam/language-haskell/issues/84

**Comment by AlexeyRaga** [comment] 2019-04-05 10:57
An immediate workaround that worked for me:

1) edit `~/.vscode/extensions/justusadam.language-haskell-2.5.0/out/src/extension.js`
2) replace `null` with `""`

**Comment by alanz** [comment] 2019-04-05 14:37
So a possible `vscode-hie-server` is to make the dependency on `language-haskell` optional, for now.

**Comment by AlexeyRaga** [comment] 2019-04-05 23:58
`language-haskell` `2.6.0` has been released, the issue is fixed now.

**Closed by AlexeyRaga** 2019-04-05 23:58 UTC
