### ISSUE TITLE
cabal-helper-wrapper fails to install cabal on WSL with "Invalid package ID"

### ISSUE THREAD

**Issue by hmemcpy** [alanz/vscode-hie-server#167] opened 2019-09-19 07:10 UTC
I've managed to (almost) set up the entire environment on WSL (with Nix). The only problem now seems to be that cabal-helper-wrapper failing to install with the following error:

```
$ /nix/store/jq8x50rkl3cm7cqkj1zsk6kfbb692iwv-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/mnt/c/dev/fp-course" "/mnt/c/dev/fp-course/dist-newstyle/build/x86_64-linux/ghc-8.6.5/course-0.1.4" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"
cabal-helper-wrapper: Installing a private copy of Cabal because we couldn't
find the right version in your global/user package-db, this might take a
while but will only happen once per Cabal version you're using.

If anything goes horribly wrong just delete this directory and try again:
    /home/hmemcpy/.cache/cabal-helper

If you want to avoid this automatic installation altogether install
version 3.0.0.0 of Cabal manually (into your user or global package-db):
    $ cabal install Cabal --constraint "Cabal == 3.0.0.0"

Installing Cabal 3.0.0.0 ...
Unpacking to Cabal-3.0.0.0/
cabal: Invalid package ID: /tmp/cabal-helper-Cabal-source5358/Cabal-3.0.0.0

cabal-helper-wrapper: Installing Cabal version 3.0.0.0 failed.
...
```
When running just with `print-build-platform`, I'm getting `x86_64-linux` as a result.

How is the tmp directory path calculated? What other details can I provide?

**Comment by hmemcpy** [comment] 2019-09-25 06:50
This also happens in this particular repo on Ubuntu proper, same error:
```
...
Installing Cabal 3.0.0.0 ...
Unpacking to Cabal-3.0.0.0/
cabal: Invalid package ID:
/run/user/1000/cabal-helper-Cabal-source16617/Cabal-3.0.0.0

cabal-helper-wrapper: Installing Cabal version 3.0.0.0 failed.
```

Any ideas?

**Comment by hmemcpy** [comment] 2019-09-25 07:50
Update: I ran with `--verbose`, saw it detecting, then trying to run cabal 3.0.0.0, and ultimately failing:
```
cd /; cabal --package-db=clear --package-db=global --package-db=/home/parallels/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0-ghc8.4.4.package-db --prefix=/home/parallels/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0-ghc8.4.4.package-db/prefix --with-ghc=/nix/store/6583ayh403bfila8xccqracxldf72f8y-ghc-8.4.4-with-packages/bin/ghc --with-ghc-pkg=/nix/store/6583ayh403bfila8xccqracxldf72f8y-ghc-8.4.4-with-packages/bin/ghc-pkg --no-require-sandbox install /run/user/1000/cabal-helper-Cabal-source12379/Cabal-3.0.0.0 -v --only-dependencies
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/CmdInstall.hs:376:25 in main:Distribution.Client.CmdInstall
cabal: Invalid package ID:
/run/user/1000/cabal-helper-Cabal-source12379/Cabal-3.0.0.0
...
```

Investigating...

**Comment by jneira** [comment] 2019-09-25 16:17
It looks very similar to #165 (in NixOS) and i've got the error in native windows too.
I think the cause is the project had been built with cabal-install-3.0.0 but the ghc used (likely 8.6.5) has installed Cabal-2.4.1.0.

**Comment by jneira** [comment] 2020-01-09 09:39
@hmemcpy hie not longer uses `cabal-helper-wrapper` so this one should be fixed, feel free to reopen if it is not the case

**Closed by jneira** 2020-01-09 09:39 UTC
