### ISSUE TITLE
cabal-install is not installed. Check the README...

### ISSUE THREAD

**Issue by janat08** [alanz/vscode-hie-server#131] opened 2019-01-20 13:08 UTC
``cabal-install is not installed. Check the README for more information`` appears, what it's actually referring to I don't know.

**Comment by delreluca** [comment] 2019-01-31 08:12
I get the same, here is the output after startup in addition.

macOS 10.14.2 x64

VSCode
Version 1.30.2 (1.30.2)
Extension
Name: Haskell Language Server
Id: alanz.vscode-hie-server
Description: Language Server Protocol for Haskell via HIE
Version: 0.0.24
Publisher: Alan Zimmerman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server
HIE
make hie-8.6.3
make build-doc-8.6.3
(Revision is in log below)

```
2019-01-31 09:01:01.949021 [ThreadId 4] - Using stack GHC version
2019-01-31 09:01:02.32697 [ThreadId 4] - Run entered for HIE(hie) Version 0.5.0.0, Git revision c4a9e7cfce86194493834839271c2aa390483048 (2382 commits) x86_64 ghc-8.6.3
2019-01-31 09:01:02.329237 [ThreadId 4] - Current directory:...
2019-01-31 09:Using hie version: Version 0.5.0.0, Git revision c4a9e7cfce86194493834839271c2aa390483048 (2382 commits) x86_64 ghc-8.6.3
01:02.382134 [ThreadId 10] - Using stack GHC version
[Warn  - 9:01:02 AM] cabal-install is not installed. Check the README for more information
Using hoogle db at: ...
```

**Comment by delreluca** [comment] 2019-02-02 22:19
It's from HIE, not from the extension, the source is here: https://github.com/haskell/haskell-ide-engine/blob/e1aeb180ab8065bd6a8413e050c6277191d0d33f/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L443

The warning basically says that there is not executable with the name cabal in the path. So either add Stacks's bin folder to the PATH (which sucks for macOS since changing the path for packaged .apps like Code needs a reboot and change in launchd configuration) or create a link to it in a location that is already in the PATH.

Maybe this could be improved in the future? In the extension I am able to provide a custom path to hie, would be nice to be able to provide one for cabal to. Of course with the current implementation of hie it is not possible.

**Comment by alanz** [comment] 2019-03-02 14:15
The install instructions on https://github.com/haskell/haskell-ide-engine suggesting using either the Makefile or (preferred now) Shake install process, which does install `cabal-install`, as it is needed by `cabal-helper`

**Comment by jchia** [comment] 2019-10-07 11:56
Has this issue been resolved? I still see the warning. I installed HIE using shake with `stack ./install.hs stack-hie-8.2.2 stack-hie-8.6.5`. I don't see `cabal`-anything in `~/.local/bin`.

**Comment by jneira** [comment] 2019-10-08 07:41
@jchia the hie build script [don't install cabal by default anymore](https://github.com/haskell/haskell-ide-engine/pull/1368), cause it should not be needed if you are using `stack`. If you want to use hie with projects that uses exclusively `cabal` (they dont have a `stack.yaml` file in root) you should install cabal:
* running `stack install.hs cabal` will install the appropiate version for hie

Maybe we should add to `stack install help` this option (currently is missing)

**Comment by jneira** [comment] 2019-10-08 10:30
I've added a visible new target to build script: `stack install.hs stack-install-cabal` to cover the use case: https://github.com/haskell/haskell-ide-engine/pull/1405

**Comment by jchia** [comment] 2019-10-08 11:57
@jneira I was getting the warning on stack projects. The warning went away after I did `stack install.hs cabal`, which added `~/.local/bin/cabal`. However, after I delete it and run `stack install.hs cabal`, nothing happens. Is that the expected behavior?

**Comment by jneira** [comment] 2019-10-08 13:04
>  I was getting the warning on stack projects

Yeah the warning should not be displayed if the project is stack based.

> Is that the expected behavior?

No, i've just reproduced the error, it seems stack finds the cabal it just installed inside $STACK_ROOT, i will change the mentioned pr to take in account that behaviour and install it every time (if it is not in the original $PATH). 
Thanks for testing!

**Comment by jneira** [comment] 2019-10-09 11:04
Finally make the install script ignore the cached cabal executable is trickier than i expected so the fix will be in another separate pr

**Comment by jneira** [comment] 2019-10-17 07:57
I've updated the README to make clear cabal is optional and the way to install it with stack: https://github.com/haskell/haskell-ide-engine/pull/1414

**Comment by jneira** [comment] 2020-01-09 08:36
hie not longer requires cabal by default and no warning message is show

**Closed by jneira** 2020-01-09 08:36 UTC
